### ISSUE TITLE
Please add a note that this will not work on Windows

### ISSUE THREAD

**Issue by JamesMGreene** [rubinius/mkrb#1]
Please add a note to the `README` that this will not work on Windows (at least, not without a Bash emulator like MinGW, Cygwin, MSysGit, GitBash, Ubuntu for Windows, etc.).

When it says it will work on my platform, I prefer to assume that it is being truthful.

**Comment by jc00ke** [comment]
Contributions are welcomed! Care to open a PR with changes to the wording?

After reading it a few times, I believe it's stating it would download a precompiled version of Ruby for whatever platform you're on, not that it would work on all platforms. That being said, if you have time to add support for Windows that would be greatly appreciated.

**Comment by JamesMGreene** [comment]
Thank you, @brixen!
